version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data: